#C:\MinGW\bin\g++.exe -g d:\ych\Git_algorithm\cpp\TestCode\helloworld.cpp -o d:\ych\Git_algorithm\cpp\TestCode\helloworld.exe
# 변수 선언
CC=g++
CFLAGS=
TARGET_PATH=./$(SRC)/
OBJS=$(TARGET_PATH)main.cpp
TARGET=$(SRC).exe
 
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET)
	$(TARGET)